### ISSUE TITLE
Logo

### ISSUE THREAD

**Issue by mubaidr** [mubaidr/image-parsing#29]
@jbeguna04 can you help me with this?

This is a desktop software.

**Comment by jbeguna04** [comment]
Greetings @mubaidr , 

Yes of course, i can help you with this in fact i enjoyed working with you in the past issue for Bulma-fluent. I would like to ask more information about the project so that i can incorporate in the logo i will create
Thank you,
Jbeguna04

**Comment by mubaidr** [comment]
I have no specific idea, lets test this one: 

> logo the represents paper/exam paper and a folder to compile those things

**Comment by jbeguna04** [comment]
thank you for your response, im still making right now :)
Ill be presenting the design asap.

**Comment by jbeguna04** [comment]
![image](https://user-images.githubusercontent.com/35353768/42015011-dc2582a8-7ad7-11e8-8a17-be0196692772.png)
This is the first proposal, what do you think?

**Comment by mubaidr** [comment]
Great! 

First one looks good, but the contrast could be better between icon and the background. What do you think?

**Comment by jbeguna04** [comment]
Yes somehow the background can be changed, Ill send you some color combinations for you to choose

**Comment by jbeguna04** [comment]
Some color combinations you could choose:
![image](https://user-images.githubusercontent.com/35353768/42019568-0e21f6a0-7ae8-11e8-9b4d-e3d10706bb59.png)

**Comment by jbeguna04** [comment]
Proposal #2:
![image](https://user-images.githubusercontent.com/35353768/42020560-c7b95fc0-7aea-11e8-897c-7a7040903aaf.png)

**Comment by mubaidr** [comment]
Can you please create logos without any background (transparent) in multiple color samples. Just like to new word, excel icons

**Comment by mubaidr** [comment]
First one in the both proposals looks good to me. But I think we should test some transparent logos too.

**Comment by jbeguna04** [comment]
![image](https://user-images.githubusercontent.com/35353768/42020789-7c10d78c-7aeb-11e8-958f-8a05abc421f9.png)

**Comment by jbeguna04** [comment]
![image](https://user-images.githubusercontent.com/35353768/42020991-11a89924-7aec-11e8-9f38-540f1aea3fa5.png)

**Comment by mubaidr** [comment]
I think this looks great.  Awesome job! Just tweak it to your liking, if you want and we are good to go. 

We will need icons in all common sizes. Create a pull request when ready and add logo & your name to read me. I will add the selected icon to the application.

**Comment by jbeguna04** [comment]
Do you have any size variations needed. And also do you have the name of the project so that i can make any banner for the readme file?

**Comment by mubaidr** [comment]
There is no name yet. So we can leave banner for now. 

Common icon sizes from 16px to 512px

**Comment by jbeguna04** [comment]
Okay @mubaidr , that was clear. Ill be sending the PR  later. Thank you for your cooperation

**Comment by jbeguna04** [comment]
Btw, should I include all of the color Variations in the PR or you had chosen any color of those?

**Comment by mubaidr** [comment]
Yes, if its comfortable for you. Otherwise blue color.
